### PR TITLE
Opinionated re-work of the README.md

### PR DESCRIPTION
**Pull request by jasonm23**
I found the wording of the README to be too loose, there were a few typos and headings were not title cased.

I've made various amendments to reduce verbosity and repetition, as well as fix up the typos and heading case.

### CODE REVIEW

**Comment by josteink** [comment]
I'm ok with those changes. Anyone else?

**Comment by justinjk007** [comment]
Me too

**Comment by jasonm23** [comment]
Thanks, I can have a look at the other docs too.

**Comment by jasonm23** [comment]
Other docs are mostly ok, I have some questions around the doc for submitting upstream patches.  I'll open an issue for that.

**Comment by josteink** [comment]
I think recent changes to Emacs (eglot, tree-sitter, etc) has helped make Emacs much more usable OOB. Considering repo-purpose obsolete.

Closing all issues and archiving repo. Thanks to all contributors!

**Pull request closed without merging**
