### PR TITLE
Increase the GC-cons threshold

### PR DESCRIPTION
**Pull request by justinjk007**
This was nicked straight from [sensible-defaults](https://github.com/hrs/sensible-defaults.el) btw. But most of us here use it I think and hey its 2017 memory is cheap.

### CODE REVIEW

**Comment by josteink** [comment]
I guess with the exception if routers, NASes and 1st gen Raspberry Pi's this is going to be a general improvement.

What's the chance of people installing Emacs and running "heavy" configs on low-end hardware? And are there any other possible objections to such a tweak we can foresee?

**Comment by justinjk007** [comment]
None that I know of.

**Comment by justinjk007** [comment]
@josteink can I merge this or is someone going to review this, @mookid  @angrybacon  @ssunday  @phillord @alandmoore get in here.

**Comment by angrybacon** [comment]
I'm only using it for the time Emacs reads my configuration files.

```elisp
(let ((gc-cons-threshold most-positive-fixnum))
  ...
  (org-babel-load-file (expand-file-name "dotemacs.org" user-emacs-directory))
  (garbage-collect))
```

Mostly because on paper, it sounded like the right thing to do. But honestly, I don't see any difference.

I also have the following:

```elisp
(add-hook 'focus-out-hook #'garbage-collect)
```

Which, likewise doesn't seem to bring much.

Though, the default value of `800000` seems really low as per 2017 standards.

**Comment by justinjk007** [comment]
+1 then ?

**Comment by angrybacon** [comment]
Yes, +1 from me. Especially when we enable more things, including Ivy.

**Comment by alandmoore** [comment]
I've been running with that tweak for about a week, it hasn't made any noticeable difference to me, so if it helps someone else, +1 from me.

**Comment by bretfh** [comment]
Stefan Monnier:

    Better not touch it. In Emacs-22 we introduced gc-cons-percentage which provides the same benefit as increasing gc-cons-threshold but without the drawbacks. And without having to fiddle with it.

    I.e. I'd recommend users to remove any gc-cons-threshold settings from their .emacs.

https://lists.gnu.org/archive/html/help-gnu-emacs/2007-06/msg00243.html

**Comment by josteink** [comment]
Good catch. I guess that settles this issue then.

**Comment by mookid** [comment]
We should be careful, as a big value of `gc-cons-threshold` induces longer GC pauses.

**Comment by justinjk007** [comment]
```lisp
(add-hook 'focus-out-hook #'garbage-collect)
```

This hook suggestd by @angrybacon serves well for me..

**Pull request merged**
