### PR TITLE
Enhanced M-x with counsel-M-x (ivy), fallback with C-c M-x

### LINKED ISSUE #47: Consider enabling counsel-M-x (ivy)
There's a discussion about enabling ivy globally (#20). My proposal (PR attached) is to at least enable `counsel-M-x`, the ivy version of `M-x` (with a fallback to `C-c M-x`). 

But this proposal is a subset of the ivy one, indeed if ivy is enabled globally it does enable this `counsel-M-x`. So let's revive the completion-framework discussion too :)

### PR DESCRIPTION
**Pull request by vindarel**
fixes #47

### CODE REVIEW

**Comment by josteink** [comment]
Is `counsel-M-x` a function supposed to be a core function, or does it come with an external package?

I can't find it.

**Comment by mookid** [comment]
It is in counsel.el in ivy.

**Comment by josteink** [comment]
So do I need to `(require)` something first or what? Doesn't work for me.

**Edit:** You need to install ivy and *then* `(require 'counsel)` for this to work.

Out of the box this patch does not work.

**Comment by vindarel** [comment]
ah, sorry, I didn't test in a fresh emacs home. The current oob-reboot test setup re-uses one's current installed packages.

**Review by ssunday — CHANGES_REQUESTED** [review]
As @josteink said, this needs to work out of the box. So we need to install counsel/ivy.

**Comment by vindarel** [comment]
Hello ! Would you try again ?

I added

```
(when (not (package-installed-p 'ivy))
  (package-initialize)
  (package-install 'ivy))
(require 'counsel)
```
this should get you going.

emacs pear_197

**Review by ssunday — APPROVED** [review]

**Comment by vindarel** [comment]
Cool ! That was quick :)

I built emacs (can't make it use a x-toolkit but no big deal for now), but finding where to `require` those packages and what to do with the occurences of `execute-extended-command` is another story.

**Comment by ssunday** [comment]
@vindarel Oh, ugh, I didn't notice that command. Usually, I just map the `M-x` to the new version and that's it.

**Comment by ssunday** [comment]
I think it's an important addition. M-x is basically unusable for people extremely new to Emacs.

**Comment by justinjk007** [comment]
Yes, suggestions will be really helpful.

**Comment by vindarel** [comment]
I suppose ivy has to be included into Emacs. It is already on Elpa (ivy on Elpa bundles ivy, swiper and counsel, they are separate on Melpa (https://github.com/abo-abo/swiper/issues/915)). I'm gonna ask.

Hello @abo-abo, have you already thought or tried to merge Ivy into Emacs ? Is it doable as of today ? (licences-wise I suppose it is, as it is on Elpa already). I suppose you are the one expected to start this process, aren't you ? do you want to ? (and any more thought to bring this issue to completion ?) Thank you !

**Comment by abo-abo** [comment]
> Hello @abo-abo, have you already thought or tried to merge Ivy into Emacs ? Is it doable as of today ? (licences-wise I suppose it is, as it is on Elpa already). I suppose you are the one expected to start this process, aren't you ? do you want to ? (and any more thought to bring this issue to completion ?) Thank you !

Ivy is already part of Emacs, just like any package on GNU ELPA.

If you're asking if ivy.el will ever be moved in together with Emacs sources, it probably won't happen, for many good reasons: looser coupling, no outdated version in the core to worry about, own bug tracker etc.

There was a thread on emacs-devel 1-2 years ago about having a version of Emacs tarball that also includes some/all GNU ELPA packages. The idea was that you could easily install these packages without connecting to the Internet. This idea hasn't yet been realized. Maybe you could lend your help, if you're interested.

**Comment by phillord** [comment]
@abo-abo I started to hack the Emacs build so that it could use package.el as part of the main build. This would make ELPA incorporation trivial, as well as meaning that packages currently in core could be moved to package.el management. It didn't go down that well. The branch is still there though http://git.savannah.gnu.org/cgit/emacs.git/log/?h=feature/integrated-elpa.

**Comment by abo-abo** [comment]
> I started to hack the Emacs build so that it could use package.el as part of the main build.
> This would make ELPA incorporation trivial, as well as meaning that packages currently in core could be moved to package.el management.

Thanks for the effort.

> It didn't go down that well

What happened? I thought many people liked the idea, including @jwiegley.

**Comment by phillord** [comment]
@abo-abo Possibly partly the implementation. I had to change the build significantly (and package.el hacking would have to have happened). The simpler solution is just for the Emacs build to know where ELPA has been checked out, then copy the files across. I dislike this because then the same files are being packaged in two different ways. Also, I think, moving all emacs packages over to being packages in the package.el sense is a good thing.

https://lists.gnu.org/archive/html/emacs-devel/2016-10/msg00030.html

The simpler approach (copying stuff during build) would probably get accepted.

**Comment by josteink** [comment]
I think recent changes to Emacs (eglot, tree-sitter, etc) has helped make Emacs much more usable OOB. Considering repo-purpose obsolete.

Closing all issues and archiving repo. Thanks to all contributors!

**Pull request closed without merging**
