### PR TITLE
added scrolling

### PR DESCRIPTION
**Pull request by mguzmann**
A more intuitive scrolling default with only half scrolling.

### CODE REVIEW

**Comment by angrybacon** [comment]
Why not customize `next-screen-context-lines` instead?

**Comment by josteink** [comment]
I agree with @angrybacon. Seeing the `defun`-statements here kind of gives me the wrong vibes...

**Comment by dchrzanowski** [comment]
I also agree that this is more of a custom setting that someone would prefer, rather than an OOB default.

**Comment by mguzmann** [comment]
Besides the poor implementation, do you guys really like the full scrolling? that was the worst part of default emacs for me. But oh well.

**Comment by angrybacon** [comment]
I would use it all the time if there was some sort of animated scrolling. It's really hard to keep track of the context, even with a higher value for the variable I mentioned earlier. 

It's still in my todo to be perfected but one use I have of it is to scroll the preview of the candidates in a Helm session and when using `isearch`.

**Comment by dchrzanowski** [comment]
@mguzmann I don't like full scrolling I use half window as well, I use that via evil-mode's 'evil-scroll-up nil' and 'evil-scroll-down nil'. I still think that this is something more individual than global. (aren't most of users using the mouse wheel anyway?)

**Comment by angrybacon** [comment]
@Grimscythe1983 New users are at least.

**Comment by dchrzanowski** [comment]
@angrybacon indeed, indeed

**Comment by mguzmann** [comment]
The question what the expected default behavior should be. I don't think any new user expects full scrolling by default.

**Comment by josteink** [comment]
> Besides the poor implementation, do you guys really like the full scrolling? that was the worst part of default emacs for me. But oh well.

I must admit I do find it confusing (even as a seasoned Emacs-user), and I seriously doubt I'm alone in that.

As I understand it, the main criticism in this thread has not been about the intent, but the implementation. Or did I misunderstand anything?

**Comment by dchrzanowski** [comment]
@mguzmann I presume that you have taken your code from [here](https://www.emacswiki.org/emacs/HalfScrolling) . Looking at the wiki it does seem like the most sane solution without any external packages (`next-screen-context-lines` is height of window dependent, so you'll need a `defun` anyway).... In that case I suggest a merge.

**Comment by mguzmann** [comment]
@Grimscythe1983 yes, I took it from there.

**Comment by angrybacon** [comment]
@mguzmann Well, I can't test what <kbd>Page Down</kbd> and <kbd>Page Up</kbd> do with `less` or `more` but if they behave like <kbd>Space</kbd>, they scroll full page don't they? After all the key itself conveys full page scroll.

**Comment by josteink** [comment]
I think recent changes to Emacs (eglot, tree-sitter, etc) has helped make Emacs much more usable OOB. Considering repo-purpose obsolete.

Closing all issues and archiving repo. Thanks to all contributors!

**Pull request closed without merging**
